name: Github Action Test Workflow

on:
  push:
    branches:
      - develop
    
jobs:
  penneo-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Determine deployment destination
        run: |          
          DESTINATION="dev"
          # DESTINATION Deployment
          echo "DESTINATION=$DESTINATION" >> $GITHUB_ENV
            
      - name: Notify Slack channel
        id: slack-start
        uses: slackapi/slack-github-action@v1.17.0
        with:
          payload: |
            {
              "text": "Starting Deployment to ${{ env.DESTINATION }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK 

      - name: Notify Slack channel
        id: slack-result
        uses: slackapi/slack-github-action@v1.17.0
        with:
          payload: |
            {
              "text": "GitHub Action deploy result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action deploy result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK 